# Assignment #4: NumPy + A few tuples/lists




### In this assignment, we will practice on NumPy, Tuple, Set, Dict using social network use case. 

**Please read the explanation in "H4.docx"**

# **Important**
- Do not delete or modify the first line in the given code cell.
- You work must be add in the provided area only. 
- You must not change the declaration of the provided functions.
- You are allowed to add your own functions.
- If you want to write your own program to test, add new code cell at the very end of the file and add your code there.


In [31]:
import numpy as np

In [32]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#1

def generate_adjacency_matrix(filename):
  # write your code here
  fn = open(filename,"r")
  r = {}
  t = set()
  for line in fn :
    a = line.strip().split(",")
    t.add(a[0])
    if a[0] not in r :
      r[a[0]] = set()
    r[a[0]].add(a[1])
  A = np.zeros((len(r),len(r)),int)
  person_names = list(dict.keys(r))
  for key in r :
    r[key] = list(r[key])
    for i in range(len(r[key])) :
      r[key][i] = person_names.index(r[key][i])
  for key in r :
    A[person_names.index(key), r[key]] = 1

  return A, person_names

In [33]:
# from google.colab import files
# uploaded = files.upload()
# print('uploaded = ', uploaded)

A, person_names = generate_adjacency_matrix("social_network.txt")
print(A)
print(person_names)

[[0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 

In [34]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#2

def get_degree_matrix(A):
  # write your code here
  D = np.zeros((len(A),len(A[0])),int)
  for i in range(len(A)) :
    D[i,i] = np.sum(A[i])



  return D

In [35]:
D = get_degree_matrix(A)
print(D)

[[24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0

In [36]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#3

def get_names_with_highest_number_of_friends(D, person_names):
  # write your code here
  max = list(np.where(D == np.max(D)))
  all_max = []
  for i in list(max[0]) :
    all_max.append((person_names[i],i))

  return all_max

In [37]:
persons = get_names_with_highest_number_of_friends(D, person_names)
print(persons)

[('B', 1), ('C', 2), ('D', 3), ('E', 4), ('F', 5), ('H', 7), ('I', 8), ('J', 9), ('K', 10), ('L', 11), ('M', 12), ('N', 13), ('O', 14), ('P', 15), ('Q', 16), ('R', 17), ('S', 18), ('T', 19), ('U', 20), ('V', 21), ('W', 22), ('X', 23), ('Y', 24), ('Z', 25)]


In [38]:
# HELPER FUNCTION
def get_liked_page_matrix(infile):
  liked_pages = []
  persons = []
  fr = open(infile, 'r')
  for line in fr:
    name, bits = line.strip().split(',')
    liked_page = [int(c) for c in bits]
    liked_pages.append(liked_page)
    persons.append(name)
  liked_pages_array = np.array(liked_pages)
  return liked_pages_array,persons

In [39]:

# from google.colab import files
# uploaded = files.upload()
# print('uploaded = ', uploaded)

liked_pages, persons = get_liked_page_matrix('liked_pages.txt')
print(liked_pages)
print(persons)


[[0 1 0 1 1 1 0 1 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0]
 [1 0 0 1 0 1 1 0 0 1 0 1 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0]
 [0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 1]
 [1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1]
 [0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0]
 [1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0]
 [0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 1]
 [1 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1]
 [0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0]
 [0 1 1 1 0 0 0 1 1 1 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0]
 [1 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1]
 [0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1]
 [1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1]
 [1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 0 1 1 1 0 0 1]
 [1 0 0 1 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 0]
 [1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 

In [40]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#4

def get_distance_matrix(Lp):
  # write your code here
  # data = np.array([[]])
  # data=np.concatenate((data,Lp))
  data = Lp.copy()
  for i in range(len(data)) :
    for j in range(len(data[i])) :
      if data[i][j] != 0 :
        data[i][j] = j
  distance_matrix = np.zeros((len(Lp),len(Lp)),float)
  for i in range(len(distance_matrix)):
    for j in range(len(distance_matrix)):
      if i == j :
        distance_matrix[i][j] = 0
      else :
        x = set(data[i])-{0}
        y = set(data[j])-{0}
        c = len(x.intersection(y))
        a = (Lp[i] == 1).sum()
        b = (Lp[j] == 1).sum()
        distance_matrix[i][j] = c / (a+b-c)
  




  return distance_matrix

In [41]:
Dt = get_distance_matrix(liked_pages)
print(Dt)

[[0.         0.4        0.09090909 0.375      0.625      0.36363636
  0.09090909 0.44444444 0.375      0.27272727 0.16666667 0.42857143
  0.16666667 0.1        0.1        0.27272727 0.25       0.22222222
  0.4        0.         0.18181818 0.25       0.5        0.55555556
  0.28571429 0.33333333]
 [0.4        0.         0.27272727 0.13043478 0.36363636 0.61904762
  0.27272727 0.42857143 0.44444444 0.45454545 0.28       0.2
  0.39130435 0.23809524 0.3        0.39130435 0.41176471 0.18181818
  0.23076923 0.         0.5        0.2        0.27272727 0.6
  0.         0.27272727]
 [0.09090909 0.27272727 0.         0.22222222 0.08333333 0.36363636
  1.         0.3        0.22222222 0.27272727 0.27272727 0.25
  0.75       0.22222222 0.375      0.4        0.11111111 0.375
  0.27272727 0.14285714 0.625      0.25       0.09090909 0.16666667
  0.125      0.33333333]
 [0.375      0.13043478 0.22222222 0.         0.2        0.2173913
  0.22222222 0.41176471 0.11111111 0.08333333 0.23809524 0.5
  0.36

In [42]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#5

def get_all_most_similar_pairs(Dt, persons):
  # write your code here
  # print(np.where(Dt == np.max(Dt)))
  # print(persons)
  max = list(np.where(Dt == np.max(Dt)))
  pairs = []
  for i in range(len(max)) :
    x=tuple(sorted((persons[max[i][0]],persons[max[i][1]])))
    if x not in pairs:
      pairs.append(x)


  return pairs

In [43]:
pairs = get_all_most_similar_pairs(Dt, persons)
print(pairs)

[('C', 'G')]


In [44]:
A, person_names = generate_adjacency_matrix("social_network.txt")
D = get_degree_matrix(A)
persons = get_names_with_highest_number_of_friends(D, person_names)
liked_pages, persons = get_liked_page_matrix('liked_pages.txt')
Dt = get_distance_matrix(liked_pages)
pairs = get_all_most_similar_pairs(Dt, persons)
print(A)
print(person_names)
print(D)
print(persons)
print(liked_pages)
print(persons)
print(Dt)
print(pairs)

[[0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 