# Assignment #4: NumPy + A few tuples/lists




### In this assignment, we will practice on NumPy, Tuple, Set, Dict using social network use case. 

**Please read the explanation in "H4.docx"**

# **Important**
- Do not delete or modify the first line in the given code cell.
- You work must be add in the provided area only. 
- You must not change the declaration of the provided functions.
- You are allowed to add your own functions.
- If you want to write your own program to test, add new code cell at the very end of the file and add your code there.


In [1]:
import numpy as np

In [2]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#1

def generate_adjacency_matrix(filename):
  # write your code here
  infile = open(filename, 'r')
  lines = [line.strip() for line in infile]
  c = 0
  member = []
  for i in range(len(lines)) :
    lines[i] = lines[i].split(',')
    for name in lines[i] :
      if name not in member :
        c += 1
        member.append(name)
  A = np.zeros((c,c),int)
  for i in range(len(lines)) : 
    r = member.index(lines[i][0])
    c = member.index(lines[i][1])
    A[r,c] = 1
  person_names = member

  return A, person_names


In [3]:
"""
from google.colab import files
uploaded = files.upload()
print('uploaded = ', uploaded)
"""
A, person_names = generate_adjacency_matrix("social_network.txt")
print(A)
print(person_names)

[[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 

In [4]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#2

def get_degree_matrix(A):
  # write your code here
  D = np.zeros((A.shape[0],A.shape[1]),int)
  for i in range(A.shape[0]) :
    count = 0
    for j in range(A.shape[1]) :
      if A[i,j] == 1 :
        count += 1
    D[i,i] = count
  
  return D


In [5]:
D = get_degree_matrix(A)
print(D)

[[24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0
   0  0]
 [ 0

In [6]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#3

def get_names_with_highest_number_of_friends(D, person_names):
  # write your code here
  value = []
  for i in range(D.shape[0]) :
    for j in range(D.shape[1]) :
      if D[i,j] not in value :
        value.append(D[i,j])
  sortvalue = sorted(value)
  all_max = []
  for i in range(D.shape[0]) :
    for j in range(D.shape[1]) :
      if D[i,j] == sortvalue[-1] :
        all_max.append([person_names[i],i])
  all_max = [tuple(e) for e in all_max]     

  return all_max


In [7]:
persons = get_names_with_highest_number_of_friends(D, person_names)
print(persons)

[('B', 1), ('C', 2), ('D', 3), ('E', 4), ('F', 5), ('H', 6), ('I', 7), ('J', 8), ('K', 9), ('L', 10), ('M', 11), ('N', 12), ('O', 13), ('P', 14), ('Q', 15), ('R', 16), ('S', 17), ('T', 18), ('U', 19), ('V', 20), ('W', 21), ('X', 22), ('Y', 23), ('Z', 24)]


In [8]:
# HELPER FUNCTION
def get_liked_page_matrix(infile):
  liked_pages = []
  persons = []
  fr = open(infile, 'r')
  for line in fr:
    name, bits = line.strip().split(',')
    liked_page = [int(c) for c in bits]
    liked_pages.append(liked_page)
    persons.append(name)
  liked_pages_array = np.array(liked_pages)
  return liked_pages_array,persons

In [9]:
"""
from google.colab import files
uploaded = files.upload()
print('uploaded = ', uploaded)
"""
liked_pages, persons = get_liked_page_matrix('liked_pages.txt')
print(liked_pages)
print(persons)


[[0 1 0 1 1 1 0 1 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0]
 [1 0 0 1 0 1 1 0 0 1 0 1 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0]
 [0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 1]
 [1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1]
 [0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0]
 [1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0]
 [0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 1]
 [1 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1]
 [0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0]
 [0 1 1 1 0 0 0 1 1 1 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0]
 [1 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1]
 [0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1]
 [1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1]
 [1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 0 1 1 1 0 0 1]
 [1 0 0 1 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 0]
 [1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 

In [10]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#4

def get_distance_matrix(Lp):
  # write your code here
  s = Lp.shape[0]
  distance_matrix = np.zeros((s,s),float)
  for i in range(distance_matrix.shape[0]) :
    for j in range(distance_matrix.shape[1]) :
      # compare rows = Lp[i,:] and Lp[j,:]
      row1 = Lp[i,:]
      row2 = Lp[j,:]
      a = 0
      for value in row1 :
        if value == 1 :
          a += 1
      b = 0
      for value in row2 :
        if value == 1 :
          b += 1
      #find c 
      c = 0
      for x in range(Lp.shape[1]) :
        if row1[x] == 1 and row1[x] == row2[x] :
          c += 1
      tanito = c / (a+b-c)
      if i != j :
        distance_matrix[i,j] = tanito
    
  return distance_matrix
get_distance_matrix(liked_pages)
  

array([[0.        , 0.4       , 0.09090909, 0.375     , 0.625     ,
        0.36363636, 0.09090909, 0.44444444, 0.375     , 0.27272727,
        0.16666667, 0.42857143, 0.16666667, 0.1       , 0.1       ,
        0.27272727, 0.25      , 0.22222222, 0.4       , 0.        ,
        0.18181818, 0.25      , 0.5       , 0.55555556, 0.28571429,
        0.33333333],
       [0.4       , 0.        , 0.27272727, 0.18181818, 0.36363636,
        0.7       , 0.27272727, 0.5       , 0.44444444, 0.45454545,
        0.33333333, 0.2       , 0.45454545, 0.3       , 0.3       ,
        0.45454545, 0.5       , 0.18181818, 0.23076923, 0.        ,
        0.5       , 0.2       , 0.27272727, 0.6       , 0.        ,
        0.27272727],
       [0.09090909, 0.27272727, 0.        , 0.22222222, 0.08333333,
        0.36363636, 1.        , 0.3       , 0.22222222, 0.27272727,
        0.27272727, 0.25      , 0.75      , 0.22222222, 0.375     ,
        0.4       , 0.11111111, 0.375     , 0.27272727, 0.14285714,
      

In [11]:
Dt = get_distance_matrix(liked_pages)
print(Dt)

[[0.         0.4        0.09090909 0.375      0.625      0.36363636
  0.09090909 0.44444444 0.375      0.27272727 0.16666667 0.42857143
  0.16666667 0.1        0.1        0.27272727 0.25       0.22222222
  0.4        0.         0.18181818 0.25       0.5        0.55555556
  0.28571429 0.33333333]
 [0.4        0.         0.27272727 0.18181818 0.36363636 0.7
  0.27272727 0.5        0.44444444 0.45454545 0.33333333 0.2
  0.45454545 0.3        0.3        0.45454545 0.5        0.18181818
  0.23076923 0.         0.5        0.2        0.27272727 0.6
  0.         0.27272727]
 [0.09090909 0.27272727 0.         0.22222222 0.08333333 0.36363636
  1.         0.3        0.22222222 0.27272727 0.27272727 0.25
  0.75       0.22222222 0.375      0.4        0.11111111 0.375
  0.27272727 0.14285714 0.625      0.25       0.09090909 0.16666667
  0.125      0.33333333]
 [0.375      0.18181818 0.22222222 0.         0.2        0.27272727
  0.22222222 0.5        0.11111111 0.08333333 0.3        0.5
  0.44444444

In [12]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#5

def get_all_most_similar_pairs(Dt, persons):
  # write your code here
  value = []
  for i in range(Dt.shape[0]) :
    for j in range(Dt.shape[1]) :
      if Dt[i,j] not in value :
        value.append(Dt[i,j])
  #print(sorted(value))

  p = []
  for i in range(Dt.shape[0]) :
    for j in range(Dt.shape[1]) :
      if Dt[i,j] == sorted(value)[-1] :
        p.append(sorted([persons[j],persons[i]]))

  setp = []
  for elem in p :
    if elem not in setp:
      setp.append(elem) 
  pairs = [tuple(e) for e in setp]
  
  return pairs



In [14]:
pairs = get_all_most_similar_pairs(Dt, persons)
print(pairs)

[('C', 'G')]


In [15]:
A, person_names = generate_adjacency_matrix("social_network.txt")
D = get_degree_matrix(A)
persons = get_names_with_highest_number_of_friends(D, person_names)
liked_pages, persons = get_liked_page_matrix('liked_pages.txt')
Dt = get_distance_matrix(liked_pages)
pairs = get_all_most_similar_pairs(Dt, persons)
print(A)
print(person_names)
print(D)
print(persons)
print(liked_pages)
print(persons)
print(Dt)
print(pairs)

[[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 